import mlgw
import mlgw.GW_generator as generator
import mlgw.EM_MoE as MoE
import numpy as np
import matplotlib.pyplot as plt


import mlgw.GW_generator as generator

	#generating the wave
generator = generator.GW_generator("TD") #creating an istance of the generator
theta = np.array([[20,10,0.5,-0.3],[70,10,0.5,-0.3]]) #list of parameters to be given to generator [m1,m2,s1,s2]
times = np.linspace(-12,0.017, 100000) #time grid at which waves shall be evaluated
amp, ph = generator.get_WF(theta, plus_cross = False, x_grid = times, red_grid = False) #returns amplitude and phase of the wave

generator.model_summary() #printing model summary

    #plotting the wave
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.title("Waves generated by a BBH with orbital parameters [m1,m2,s1,s2] = "+str(theta))
#plt.plot(times, amp[0,:]*np.exp(1j*ph[0,:]).real) #plot the plus polarization
plt.plot(times, ph[0,:], label = "2")
plt.plot(times, ph[1,:])
plt.legend()
plt.show()


